-- Insert sample blessings for Daily Blessings - Morning
INSERT INTO blessings (category_id, subcategory_id, title, content, content_type, author, meta_title, meta_description, meta_keywords, is_featured) VALUES
((SELECT id FROM categories WHERE slug = 'daily-blessings'), (SELECT id FROM subcategories WHERE slug = 'morning'), 'Good Morning Blessing', 'May this morning bring you peace, joy, and countless blessings. May your day be filled with love, laughter, and beautiful moments that warm your heart.', 'short', 'BlessYou.Today', 'Good Morning Blessing - Start Your Day Right', 'Beautiful good morning blessing to start your day with positivity and joy', 'good morning blessing, morning prayer, daily blessing', true),
((SELECT id FROM categories WHERE slug = 'daily-blessings'), (SELECT id FROM subcategories WHERE slug = 'morning'), 'Morning Prayer of Gratitude', 'Dear Lord, as I wake to this new day, I am grateful for the gift of life, for the breath in my lungs, and for the opportunities that await. Guide my steps, bless my words, and help me to be a source of light and love to all I encounter today. Amen.', 'long', 'BlessYou.Today', 'Morning Prayer of Gratitude - Daily Spiritual Blessing', 'Start your morning with this beautiful prayer of gratitude and spiritual reflection', 'morning prayer, gratitude prayer, daily spiritual blessing', false),
((SELECT id FROM categories WHERE slug = 'daily-blessings'), (SELECT id FROM subcategories WHERE slug = 'morning'), 'Sunrise Blessing', 'Like the sun that rises each morning, may hope rise in your heart today. May you find strength in new beginnings and joy in simple moments.', 'short', 'BlessYou.Today', 'Sunrise Blessing - Hope and New Beginnings', 'Inspirational sunrise blessing about hope and new beginnings for your morning', 'sunrise blessing, hope blessing, new beginnings', false);

-- Insert sample blessings for Daily Blessings - Evening
INSERT INTO blessings (category_id, subcategory_id, title, content, content_type, author, meta_title, meta_description, meta_keywords, is_featured) VALUES
((SELECT id FROM categories WHERE slug = 'daily-blessings'), (SELECT id FROM subcategories WHERE slug = 'evening'), 'Evening Peace Blessing', 'As the day comes to a close, may peace fill your heart and rest restore your soul. May you sleep soundly knowing you are loved and blessed.', 'short', 'BlessYou.Today', 'Evening Peace Blessing - End Your Day in Tranquility', 'Beautiful evening blessing for peace and restful sleep', 'evening blessing, peace blessing, good night blessing', false),
((SELECT id FROM categories WHERE slug = 'daily-blessings'), (SELECT id FROM subcategories WHERE slug = 'evening'), 'Gratitude Evening Prayer', 'Heavenly Father, as this day draws to an end, I thank You for Your countless blessings. For the challenges that made me stronger, for the joys that filled my heart, and for Your constant presence in my life. Watch over me and my loved ones through the night, and grant us peaceful rest. In Your holy name, Amen.', 'long', 'BlessYou.Today', 'Gratitude Evening Prayer - Thankful End to Your Day', 'End your day with this heartfelt evening prayer of gratitude and thanksgiving', 'evening prayer, gratitude prayer, thankful blessing', false);

-- Insert sample blessings for Birthday Blessings - Friends
INSERT INTO blessings (category_id, subcategory_id, title, content, content_type, author, meta_title, meta_description, meta_keywords, is_featured) VALUES
((SELECT id FROM categories WHERE slug = 'birthday-blessings'), (SELECT id FROM subcategories WHERE slug = 'friends'), 'Birthday Blessing for a Dear Friend', 'On your special day, may you be surrounded by love, filled with joy, and blessed with all the happiness your heart can hold. Happy Birthday, dear friend!', 'short', 'BlessYou.Today', 'Birthday Blessing for a Dear Friend - Special Birthday Wishes', 'Heartfelt birthday blessing for your dear friend on their special day', 'birthday blessing for friend, friend birthday wishes, happy birthday blessing', true),
((SELECT id FROM categories WHERE slug = 'birthday-blessings'), (SELECT id FROM subcategories WHERE slug = 'friends'), 'Friendship Birthday Prayer', 'Dear God, I thank You for the gift of friendship and for this wonderful person who brings so much joy into my life. On their birthday, I pray that You would bless them abundantly - with health, happiness, love, and all the desires of their heart. May this new year of life be filled with Your grace and countless beautiful moments. Amen.', 'long', 'BlessYou.Today', 'Friendship Birthday Prayer - Blessing for Friend''s Birthday', 'Beautiful birthday prayer blessing for your friend''s special day', 'friendship birthday prayer, birthday blessing prayer, friend birthday blessing', false);

-- Insert sample blessings for Wedding & Anniversary - Bride
INSERT INTO blessings (category_id, subcategory_id, title, content, content_type, author, meta_title, meta_description, meta_keywords, is_featured) VALUES
((SELECT id FROM categories WHERE slug = 'wedding-anniversary-blessings'), (SELECT id FROM subcategories WHERE slug = 'bride'), 'Bride''s Wedding Day Blessing', 'May your wedding day be the beginning of a lifetime filled with love, laughter, and endless joy. May your marriage be blessed with understanding, patience, and a love that grows stronger with each passing day.', 'short', 'BlessYou.Today', 'Bride''s Wedding Day Blessing - Beautiful Wedding Wishes', 'Special wedding day blessing for the bride on her most important day', 'bride wedding blessing, wedding day blessing, bride blessing', true),
((SELECT id FROM categories WHERE slug = 'wedding-anniversary-blessings'), (SELECT id FROM subcategories WHERE slug = 'bride'), 'Prayer for the Bride', 'Heavenly Father, we lift up this beautiful bride to You on her wedding day. Bless her with wisdom to be a loving wife, strength to face life''s challenges alongside her husband, and joy that overflows from a heart filled with Your love. May her marriage be a reflection of Your perfect love, and may she find in her husband a partner, best friend, and companion for life. Guide them both as they begin this sacred journey together. In Jesus'' name, Amen.', 'long', 'BlessYou.Today', 'Prayer for the Bride - Wedding Day Prayer Blessing', 'Heartfelt prayer blessing for the bride on her wedding day', 'bride prayer, wedding prayer for bride, bride blessing prayer', false);

-- Insert sample blessings for Religious Blessings - Christian
INSERT INTO blessings (category_id, subcategory_id, title, content, content_type, author, meta_title, meta_description, meta_keywords, is_featured) VALUES
((SELECT id FROM categories WHERE slug = 'religious-blessings'), (SELECT id FROM subcategories WHERE slug = 'christian'), 'Numbers 6:24-26 Blessing', 'The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you; the Lord turn his face toward you and give you peace.', 'short', 'Bible - Numbers 6:24-26', 'Numbers 6:24-26 Blessing - Biblical Blessing', 'The beautiful Aaronic blessing from Numbers 6:24-26 in the Bible', 'Numbers 6:24-26, biblical blessing, Aaronic blessing, Christian blessing', true),
((SELECT id FROM categories WHERE slug = 'religious-blessings'), (SELECT id FROM subcategories WHERE slug = 'christian'), 'Christian Daily Prayer', 'Almighty God, Creator of heaven and earth, I come before You this day with a heart full of gratitude. Thank You for Your unfailing love, Your mercy that is new every morning, and Your grace that sustains me. Guide my steps according to Your will, help me to love others as You have loved me, and use me as an instrument of Your peace in this world. May everything I do today bring glory to Your holy name. Through Jesus Christ our Lord, Amen.', 'long', 'BlessYou.Today', 'Christian Daily Prayer - Morning Prayer Blessing', 'Beautiful Christian daily prayer to start your day with God', 'Christian daily prayer, morning prayer, Christian blessing prayer', false);

-- Insert sample blessings for Life Events - New Baby
INSERT INTO blessings (category_id, subcategory_id, title, content, content_type, author, meta_title, meta_description, meta_keywords, is_featured) VALUES
((SELECT id FROM categories WHERE slug = 'life-events'), (SELECT id FROM subcategories WHERE slug = 'new-baby'), 'New Baby Blessing', 'May this precious little one be blessed with health, happiness, and a lifetime of love. May they grow in wisdom and grace, bringing joy to all who know them.', 'short', 'BlessYou.Today', 'New Baby Blessing - Welcoming a Precious Life', 'Beautiful blessing for a new baby and their family', 'new baby blessing, baby blessing, newborn blessing', true),
((SELECT id FROM categories WHERE slug = 'life-events'), (SELECT id FROM subcategories WHERE slug = 'new-baby'), 'Prayer for New Parents', 'Loving Father, we thank You for the miracle of new life and for this precious baby You have entrusted to these parents. Bless this child with good health, a curious mind, and a loving heart. Give the parents wisdom, patience, and strength as they nurture and guide this little one. May their home be filled with laughter, love, and Your divine presence. Surround this family with Your protection and grace, and help them to raise this child in Your ways. In Your holy name we pray, Amen.', 'long', 'BlessYou.Today', 'Prayer for New Parents - Baby Blessing Prayer', 'Heartfelt prayer blessing for new parents and their baby', 'new parents prayer, baby blessing prayer, new baby prayer', false);

-- Insert sample blessings for Holiday Blessings - Christmas
INSERT INTO blessings (category_id, subcategory_id, title, content, content_type, author, meta_title, meta_description, meta_keywords, is_featured) VALUES
((SELECT id FROM categories WHERE slug = 'holiday-blessings'), (SELECT id FROM subcategories WHERE slug = 'christmas'), 'Christmas Family Blessing', 'May the joy of Christmas fill your home, the love of family warm your heart, and the peace of Christ be with you throughout the holiday season and beyond.', 'short', 'BlessYou.Today', 'Christmas Family Blessing - Holiday Joy and Peace', 'Beautiful Christmas blessing for family gatherings and holiday celebrations', 'Christmas blessing, Christmas family blessing, holiday blessing', true),
((SELECT id FROM categories WHERE slug = 'holiday-blessings'), (SELECT id FROM subcategories WHERE slug = 'christmas'), 'Christmas Prayer of Gratitude', 'Heavenly Father, as we celebrate the birth of Your Son Jesus Christ, our hearts overflow with gratitude for the greatest gift ever given - Your love made manifest in human form. Thank You for the hope He brings, the salvation He offers, and the peace He provides. Bless our family gatherings, our shared meals, and our time together. Help us to remember those who are lonely, hungry, or in need during this season, and show us how to be Your hands and feet in serving others. May the true meaning of Christmas - Your incredible love for us - fill our hearts and homes with joy, peace, and goodwill toward all. In Jesus'' precious name, Amen.', 'long', 'BlessYou.Today', 'Christmas Prayer of Gratitude - Holiday Prayer Blessing', 'Meaningful Christmas prayer of gratitude and thanksgiving', 'Christmas prayer, Christmas gratitude prayer, holiday prayer blessing', false);

-- Insert sample blessings for Sympathy & Healing - Condolences
INSERT INTO blessings (category_id, subcategory_id, title, content, content_type, author, meta_title, meta_description, meta_keywords, is_featured) VALUES
((SELECT id FROM categories WHERE slug = 'sympathy-healing'), (SELECT id FROM subcategories WHERE slug = 'condolences'), 'Sympathy Blessing', 'May you find comfort in loving memories, strength in the support of family and friends, and peace in knowing that love never dies.', 'short', 'BlessYou.Today', 'Sympathy Blessing - Comfort in Times of Loss', 'Gentle sympathy blessing to offer comfort during times of grief and loss', 'sympathy blessing, condolence blessing, grief comfort', false),
((SELECT id FROM categories WHERE slug = 'sympathy-healing'), (SELECT id FROM subcategories WHERE slug = 'condolences'), 'Prayer for Those Who Grieve', 'Compassionate God, we lift up to You those who are grieving the loss of someone dear. Wrap them in Your loving arms and comfort them in their sorrow. Help them to find peace in their memories, strength in Your presence, and hope in the promise of eternal life. Surround them with caring friends and family who can offer support during this difficult time. May they feel Your love sustaining them through each day, and may they find healing for their broken hearts. In Your mercy and grace, Amen.', 'long', 'BlessYou.Today', 'Prayer for Those Who Grieve - Comfort and Healing', 'Compassionate prayer for those experiencing grief and loss', 'grief prayer, sympathy prayer, condolence prayer, healing prayer', false);